// src/components/action-sheet/header/index.jsx
import classNames from 'classnames'

export default {
  name: 'ActionSheetHeader',
  props: {
    className: {
      type: [Array, String],
      default: () => '',
    },
  },
  render() {
    const rootClass = classNames('at-action-sheet__header', this.className)

    return <view className={rootClass}>{this.$slots.default}</view>
  },
}

// packages/taro-ui-vue/src/components/action-sheet/components/header.vue
<template>
  <view :class="rootClass">
    <slot />
  </view>
</template>

<script lang="ts">
import classNames from 'classnames'

export default {
  name: 'ActionSheetHeader',
  props: {
    className: {
      type: [Array, String],
      default: () => '',
    },
  },
  computed: {
    rootClass() {
      return classNames('at-action-sheet__header', this.className)
    },
  },
}
</script>
