// src/components/action-sheet/body/item/index.jsx
import classNames from 'classnames'

export default {
  name: 'ActionSheetItem',
  props: {
    className: {
      type: [Array, String],
      default: () => '',
    },
    onClick: {
      type: Function,
      default: () => () => {},
    },
  },
  methods: {
    handleClick(e) {
      this.onClick && this.onClick(e)
    },
  },
  render() {
    const rootClass = classNames('at-action-sheet__item', this.className)

    return (
      <view className={rootClass} onTap={this.handleClick}>
        {this.slots.default}
      </view>
    )
  },
}

// packages/taro-ui-vue/src/components/action-sheet/components/item.vue
<template>
  <view
    :class="rootClass"
    @tap="handleClick"
    @click="handleClick"
  >
    <slot />
  </view>
</template>

<script>
import classNames from 'classnames'

export default {
  name: 'AtActionSheetItem',
  props: {
    className: {
      type: [Array, String],
      default: () => '',
    },
    onClick: {
      type: Function,
      default: () => () => {},
    },
  },
	computed: {
		rootClass() {
			return classNames('at-action-sheet__item', this.className)
		}
	},
  methods: {
    handleClick(e) {
      this.onClick && this.onClick(e)
    },
	},
}
</script>
