// packages/taro-ui-vue/src/components/action-sheet/components/footer.vue
<template>
  <view :class="rootClass" @tap="handleClick" @click="handleClick">
    <slot />
  </view>
</template>

<script lang="ts">
import classNames from 'classnames'

export default {
  name: 'ActionSheetHeader',
  props: {
    className: {
      type: [Array, String],
      default: () => '',
    },
    onClick: {
      type: Function,
      default: () => () => {},
    },
  },
  computed: {
    rootClass() {
      return classNames('at-action-sheet__footer', this.className)
    },
  },
  methods: {
    handleClick(e) {
      this.onClick && this.onClick(e)
    },
  },
}
</script>

// src/components/action-sheet/footer/index.jsx
import classNames from 'classnames'

export default {
  name: 'ActionSheetFooter',
  props: {
    className: {
      type: [Array, String],
      default: () => '',
    },
    onClick: {
      type: Function,
      default: () => () => {},
    },
  },
  methds: {
    handleClick(e) {
      this.onClick && this.onClick(e)
    },
  },
  render() {
    const rootClass = classNames('at-action-sheet__footer', this.className)

    return (
      <view onTap={this.handleClick} className={rootClass}>
        {this.$slots.default}
      </view>
    )
  },
}
