// packages/taro-ui-vue/src/components/action-sheet/index.vue
<template>
  <view
    :class="rootClass"
    :on-touch-move="handleTouchMove"
  >
    <view
      class="at-action-sheet__overlay"
      @tap="close"
      @click="close"
    />
    <view class="at-action-sheet__container">
      <ActionSheetHeader v-if="title">
        {{ title }}
      </ActionSheetHeader>
      <ActionSheetBody>
        <slot />
      </ActionSheetBody>
      <ActionSheetFooter :on-click="handleCancel">
        {{ cancelText }}
      </ActionSheetFooter>
    </view>
  </view>
</template>

<script>
import ActionSheetBody from './components/body.vue'
import ActionSheetFooter from './components/footer.vue'
import ActionSheetHeader from './components/header.vue'
import AtActionSheet from './index'
export default {
  name: 'AtActionSheet',
  components: {
    ActionSheetBody,
    ActionSheetFooter,
    ActionSheetHeader,
  },
}
</script>

// src/components/action-sheet/index.jsx
import classNames from 'classnames'
import ActionSheetBody from './body/index'
import ActionSheetFooter from './footer/index'
import ActionSheetHeader from './header/index'

export default {
  name: 'ActionSheet',
  props: {
    title: {
      type: String,
      default: '',
    },
    cancelText: {
      type: String,
      default: '',
    },
    isOpened: {
      type: Boolean,
      default: false,
    },
    onClose: {
      type: Function,
      default: () => () => {},
    },
    onCancel: {
      type: Function,
      default: () => () => {},
    },
  },
  data() {
    return {
      show: this.isOpened,
    }
  },
  watch: {
    isOpened(val) {
      this.show = val
      !val && this.handleClose()
    },
  },
  methods: {
    handleClose() {
      if (typeof this.onClose === 'function') {
        this.onClose()
      }
    },
    handleCancel() {
      if (typeof this.onCancel === 'function') {
        return this.onCancel()
      }
      this.close()
    },
    close() {
      this.show = false
    },
    handleTouchMove(e) {
      e.stopPropagation()
      e.preventDefault()
    },
  },
  render() {
    const { title, cancelText, className } = this
    const { show } = this

    const rootClass = classNames(
      'at-action-sheet',
      {
        'at-action-sheet--active': show,
      },
      className
    )

    return (
      <view className={rootClass} onTouchMove={this.handleTouchMove}>
        <view onTap={this.close} className="at-action-sheet__overlay" />
        <view className="at-action-sheet__container">
          {title && <ActionSheetHeader>{title}</ActionSheetHeader>}
          <ActionSheetBody>{this.$slots.default}</ActionSheetBody>
          {cancelText && (
            <ActionSheetFooter onTap={this.handleCancel}>{cancelText}</ActionSheetFooter>
          )}
        </view>
      </view>
    )
  },
}
