// packages/taro-ui-vue/src/components/modal/header/index.vue
<template>
  <view :class="rootClass">
    <slot></slot>
  </view>
</template>

<script>
import classNames from 'classnames'
export default {
  name: 'AtModalHeader',
  props: {
    className: {
      type: [Object, String],
      default: '',
    },
  },
  computed: {
    rootClass() {
      return classNames('at-modal__header', this.className)
    },
  },
}
</script>

// src/components/action-sheet/header/index.jsx
import classNames from 'classnames'

export default {
  name: 'ActionSheetHeader',
  props: {
    className: {
      type: [Array, String],
      default: () => '',
    },
  },
  render() {
    const rootClass = classNames('at-action-sheet__header', this.className)

    return <view className={rootClass}>{this.$slots.default}</view>
  },
}
